import { Router, Request, Response } from 'express';
import { pool } from '../db';

const router = Router();

const ITEM_SELECT = `
  SELECT i.*,
         s.name AS supplier_name
  FROM items i
  JOIN suppliers s ON s.id = i.supplier_id
`;

const n = (v: unknown) => (v === '' || v === undefined ? null : v);

// GET /api/items?supplier_id=xxx — list all items (optionally filtered by supplier)
router.get('/', async (req: Request, res: Response) => {
  const { supplier_id } = req.query;
  try {
    const result = supplier_id
      ? await pool.query(`${ITEM_SELECT} WHERE i.supplier_id = $1 ORDER BY i.id ASC`, [supplier_id])
      : await pool.query(`${ITEM_SELECT} ORDER BY i.id ASC`);
    res.json(result.rows);
  } catch (err) {
    res.status(500).json({ error: 'Failed to fetch items' });
  }
});

// GET /api/items/:id
router.get('/:id', async (req: Request, res: Response) => {
  try {
    const result = await pool.query(`${ITEM_SELECT} WHERE i.id = $1`, [req.params.id]);
    if (result.rows.length === 0) {
      return res.status(404).json({ error: 'Item not found' });
    }
    res.json(result.rows[0]);
  } catch (err) {
    res.status(500).json({ error: 'Failed to fetch item' });
  }
});

// POST /api/items — id is auto-generated by the DB (001, 002, …)
router.post('/', async (req: Request, res: Response) => {
  const { name, supplier_id, size, unit_weight, units_in_case, cases_in_fcl } = req.body;
  if (!name || !supplier_id) {
    return res.status(400).json({ error: 'name and supplier_id are required' });
  }
  try {
    const result = await pool.query(
      `INSERT INTO items (name, supplier_id, size, unit_weight, units_in_case, cases_in_fcl)
       VALUES ($1, $2, $3, $4, $5, $6)
       RETURNING *`,
      [name, supplier_id, n(size), n(unit_weight), n(units_in_case), n(cases_in_fcl)]
    );
    res.status(201).json(result.rows[0]);
  } catch (err: any) {
    if (err.code === '23503') return res.status(400).json({ error: 'Invalid supplier_id' });
    res.status(500).json({ error: 'Failed to create item' });
  }
});

// PUT /api/items/:id — DBM catalog fields only. Pricing lives in /api/pricing.
router.put('/:id', async (req: Request, res: Response) => {
  const { name, supplier_id, size, unit_weight, units_in_case, cases_in_fcl } = req.body;

  if (!name) return res.status(400).json({ error: 'name is required' });

  try {
    const result = await pool.query(
      `UPDATE items SET
        name          = $1,
        supplier_id   = COALESCE($2, supplier_id),
        size          = $3,
        unit_weight   = $4,
        units_in_case = $5,
        cases_in_fcl  = $6
       WHERE id = $7
       RETURNING *`,
      [
        name, n(supplier_id), n(size),
        n(unit_weight), n(units_in_case), n(cases_in_fcl),
        req.params.id,
      ]
    );
    if (result.rows.length === 0) return res.status(404).json({ error: 'Item not found' });
    res.json(result.rows[0]);
  } catch (err: any) {
    if (err.code === '23503') return res.status(400).json({ error: 'Invalid supplier_id' });
    res.status(500).json({ error: 'Failed to update item' });
  }
});

// DELETE /api/items/:id
router.delete('/:id', async (req: Request, res: Response) => {
  try {
    const result = await pool.query('DELETE FROM items WHERE id = $1 RETURNING *', [req.params.id]);
    if (result.rows.length === 0) return res.status(404).json({ error: 'Item not found' });
    res.json({ message: 'Item deleted' });
  } catch (err) {
    res.status(500).json({ error: 'Failed to delete item' });
  }
});

export default router;
